services:
  # PostgreSQL 17 Database
  postgres:
    image: postgres:17-alpine
    container_name: ocr_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_NAME:-ocr_identity_db}
      POSTGRES_USER: ${DB_USERNAME:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - ocr_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME:-postgres} -d ${DB_NAME:-ocr_identity_db}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: ocr_redis
    restart: unless-stopped
    command: redis-server --appendonly yes --maxmemory 256mb --maxmemory-policy allkeys-lru
    volumes:
      - redis_data:/data
    networks:
      - ocr_network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 128M

  # MinIO Object Storage (S3 Compatible)
  minio:
    image: minio/minio:latest
    container_name: ocr_minio
    restart: unless-stopped
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER:-minioadmin}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:-minioadmin}
    ports:
      - "${MINIO_API_PORT:-9000}:9000"
      - "${MINIO_CONSOLE_PORT:-9001}:9001"
    volumes:
      - minio_data:/data
    networks:
      - ocr_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
      start_period: 30s
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 128M

  # Mailpit (Email Testing)
  mailpit:
    image: axllent/mailpit:latest
    container_name: ocr_mailpit
    restart: unless-stopped
    ports:
      - "${MAILPIT_SMTP_PORT:-1025}:1025"
      - "${MAILPIT_UI_PORT:-8025}:8025"
    networks:
      - ocr_network
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8025"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 64M

  # Main Application
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    container_name: ocr_app
    restart: unless-stopped
    ports:
      - "${APP_PORT:-8000}:${APP_PORT:-8000}"
      - "5678:5678"  # Debug port
    volumes:
      - ./:/app
    environment:
      - PYTHONUNBUFFERED=1
      - UVICORN_RELOAD=1
      - DEBUG_IP=${DEBUG_IP:-0.0.0.0}
      - APP_PORT=${APP_PORT:-8000}
      # Database
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USERNAME=${DB_USERNAME:-postgres}
      - DB_PASSWORD=${DB_PASSWORD:-postgres}
      - DB_NAME=${DB_NAME:-ocr_identity_db}
      # Redis
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=${REDIS_PASSWORD:-}
      # MinIO/S3
      - S3_AWS_ACCESS_KEY_ID=minioadmin
      - S3_AWS_SECRET_ACCESS_KEY=minioadmin
      - S3_REGION_NAME=us-east-1
      - S3_BUCKET_NAME=ocr-identity-bucket
      - S3_ENDPOINT_URL=http://minio:9000
      - S3_USE_SSL=false
      - S3_VERIFY_SSL=false
      # Email (Mailpit)
      - EMAIL_SMTP_HOST=mailpit
      - EMAIL_SMTP_PORT=1025
      - EMAIL_USERNAME=${EMAIL_USERNAME:-test@example.com}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD:-}
      - EMAIL_FROM=${EMAIL_FROM:-test@example.com}
      - EMAIL_USE_TLS=false
      - EMAIL_USE_SSL=false
      # App settings
      - SECRET_KEY=${SECRET_KEY:-your-secret-key-change-in-production}
      - DEBUG=${DEBUG:-false}
      - ENVIRONMENT=${ENVIRONMENT:-development}
      # Sentry
      - SENTRY_DSN=${SENTRY_DSN:-}
      - SENTRY_RELEASE=${SENTRY_RELEASE:-2.0.0}
      - SENTRY_SERVER_NAME=${SENTRY_SERVER_NAME:-ocr-identity-api}
      - SENTRY_ENVIRONMENT=${SENTRY_ENVIRONMENT:-development}
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      minio:
        condition: service_healthy
    networks:
      - ocr_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '2.0'
        reservations:
          memory: 1G
          cpus: '0.5'

  # Celery Worker - OCR Processing
  celery_worker_ocr:
    build:
      context: .
      dockerfile: Dockerfile
      target: celery-worker
    container_name: ocr_celery_worker_ocr
    restart: unless-stopped
    command: poetry run celery -A app.core.celery_app worker --loglevel=info --queues=ocr --concurrency=2 --hostname=worker-ocr@%h
    volumes:
      - ./:/app
    environment:
      - PYTHONUNBUFFERED=1
      # Database
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USERNAME=${DB_USERNAME:-postgres}
      - DB_PASSWORD=${DB_PASSWORD:-postgres}
      - DB_NAME=${DB_NAME:-ocr_identity_db}
      # Redis
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=${REDIS_PASSWORD:-}
      # MinIO/S3
      - S3_AWS_ACCESS_KEY_ID=minioadmin
      - S3_AWS_SECRET_ACCESS_KEY=minioadmin
      - S3_REGION_NAME=us-east-1
      - S3_BUCKET_NAME=ocr-identity-bucket
      - S3_ENDPOINT_URL=http://minio:9000
      - S3_USE_SSL=false
      - S3_VERIFY_SSL=false
      # App settings
      - SECRET_KEY=${SECRET_KEY:-your-secret-key-change-in-production}
      - DEBUG=${DEBUG:-false}
      - ENVIRONMENT=${ENVIRONMENT:-development}
      # Sentry
      - SENTRY_DSN=${SENTRY_DSN:-}
      - SENTRY_RELEASE=${SENTRY_RELEASE:-2.0.0}
      - SENTRY_SERVER_NAME=${SENTRY_SERVER_NAME:-ocr-identity-api}
      - SENTRY_ENVIRONMENT=${SENTRY_ENVIRONMENT:-development}
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      minio:
        condition: service_healthy
    networks:
      - ocr_network
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '1.0'
        reservations:
          memory: 512M
          cpus: '0.25'

  # Celery Worker - Media Processing
  celery_worker_media:
    build:
      context: .
      dockerfile: Dockerfile
      target: celery-worker
    container_name: ocr_celery_worker_media
    restart: unless-stopped
    command: poetry run celery -A app.core.celery_app worker --loglevel=info --queues=media --concurrency=4 --hostname=worker-media@%h
    volumes:
      - ./:/app
    environment:
      - PYTHONUNBUFFERED=1
      # Database
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USERNAME=${DB_USERNAME:-postgres}
      - DB_PASSWORD=${DB_PASSWORD:-postgres}
      - DB_NAME=${DB_NAME:-ocr_identity_db}
      # Redis
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=${REDIS_PASSWORD:-}
      # MinIO/S3
      - S3_AWS_ACCESS_KEY_ID=minioadmin
      - S3_AWS_SECRET_ACCESS_KEY=minioadmin
      - S3_REGION_NAME=us-east-1
      - S3_BUCKET_NAME=ocr-identity-bucket
      - S3_ENDPOINT_URL=http://minio:9000
      - S3_USE_SSL=false
      - S3_VERIFY_SSL=false
      # App settings
      - SECRET_KEY=${SECRET_KEY:-your-secret-key-change-in-production}
      - DEBUG=${DEBUG:-false}
      - ENVIRONMENT=${ENVIRONMENT:-development}
      # Sentry
      - SENTRY_DSN=${SENTRY_DSN:-}
      - SENTRY_RELEASE=${SENTRY_RELEASE:-2.0.0}
      - SENTRY_SERVER_NAME=${SENTRY_SERVER_NAME:-ocr-identity-api}
      - SENTRY_ENVIRONMENT=${SENTRY_ENVIRONMENT:-development}
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      minio:
        condition: service_healthy
    networks:
      - ocr_network
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '1.0'
        reservations:
          memory: 512M
          cpus: '0.25'

  # Celery Beat Scheduler
  celery_beat:
    build:
      context: .
      dockerfile: Dockerfile
      target: celery-worker
    container_name: ocr_celery_beat
    restart: unless-stopped
    command: poetry run celery -A app.core.celery_app beat --loglevel=info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    volumes:
      - ./:/app
    environment:
      - PYTHONUNBUFFERED=1
      # Database
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USERNAME=${DB_USERNAME:-postgres}
      - DB_PASSWORD=${DB_PASSWORD:-postgres}
      - DB_NAME=${DB_NAME:-ocr_identity_db}
      # Redis
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=${REDIS_PASSWORD:-}
      # MinIO/S3
      - S3_AWS_ACCESS_KEY_ID=minioadmin
      - S3_AWS_SECRET_ACCESS_KEY=minioadmin
      - S3_REGION_NAME=us-east-1
      - S3_BUCKET_NAME=ocr-identity-bucket
      - S3_ENDPOINT_URL=http://minio:9000
      - S3_USE_SSL=false
      - S3_VERIFY_SSL=false
      # App settings
      - SECRET_KEY=${SECRET_KEY:-your-secret-key-change-in-production}
      - DEBUG=${DEBUG:-false}
      - ENVIRONMENT=${ENVIRONMENT:-development}
      # Sentry
      - SENTRY_DSN=${SENTRY_DSN:-}
      - SENTRY_RELEASE=${SENTRY_RELEASE:-2.0.0}
      - SENTRY_SERVER_NAME=${SENTRY_SERVER_NAME:-ocr-identity-api}
      - SENTRY_ENVIRONMENT=${SENTRY_ENVIRONMENT:-development}
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - ocr_network
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.5'
        reservations:
          memory: 128M
          cpus: '0.1'

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local
  minio_data:
    driver: local

networks:
  ocr_network:
    driver: bridge