version: '3.8'

services:
  # PostgreSQL 17 Database
  postgres:
    image: postgres:17-alpine
    container_name: ocr_postgres_staging
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_NAME:-ocr_identity_db_staging}
      POSTGRES_USER: ${DB_USERNAME:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "${DB_PORT:-5433}:5432"  # Different port for staging
    volumes:
      - postgres_data_staging:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    networks:
      - ocr_network_staging
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME:-postgres} -d ${DB_NAME:-ocr_identity_db_staging}"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: ocr_redis_staging
    restart: unless-stopped
    command: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD:-}
    ports:
      - "${REDIS_PORT:-6380}:6379"  # Different port for staging
    volumes:
      - redis_data_staging:/data
    networks:
      - ocr_network_staging
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # MinIO Object Storage (S3 Compatible)
  minio:
    image: minio/minio:latest
    container_name: ocr_minio_staging
    restart: unless-stopped
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER:-minioadmin}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:-minioadmin}
    ports:
      - "${MINIO_API_PORT:-9002}:9000"  # Different port for staging
      - "${MINIO_CONSOLE_PORT:-9003}:9001"  # Different port for staging
    volumes:
      - minio_data_staging:/data
    networks:
      - ocr_network_staging
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  # Mailpit (Email Testing)
  mailpit:
    image: axllent/mailpit:latest
    container_name: ocr_mailpit_staging
    restart: unless-stopped
    ports:
      - "${MAILPIT_SMTP_PORT:-1026}:1025"  # Different port for staging
      - "${MAILPIT_UI_PORT:-8026}:8025"  # Different port for staging
    networks:
      - ocr_network_staging
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8025"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Staging Application
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: staging
    container_name: ocr_app_staging
    restart: unless-stopped
    ports:
      - "${APP_PORT:-8001}:8000"  # Different port for staging
    environment:
      - PYTHONUNBUFFERED=1
      - APP_PORT=${APP_PORT:-8001}
      - ENVIRONMENT=staging
      # Database
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USERNAME=${DB_USERNAME:-postgres}
      - DB_PASSWORD=${DB_PASSWORD:-postgres}
      - DB_NAME=${DB_NAME:-ocr_identity_db_staging}
      # Redis
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=${REDIS_PASSWORD:-}
      # MinIO (S3)
      - AWS_ACCESS_KEY_ID=${MINIO_ROOT_USER:-minioadmin}
      - AWS_SECRET_ACCESS_KEY=${MINIO_ROOT_PASSWORD:-minioadmin}
      - AWS_REGION=${AWS_REGION:-us-east-1}
      - S3_BUCKET_NAME=${S3_BUCKET_NAME:-ocr-identity-bucket-staging}
      - S3_ENDPOINT_URL=http://minio:9000
      - S3_USE_SSL=false
      - S3_VERIFY_SSL=false
      # Email (Mailpit)
      - EMAIL_SMTP_HOST=mailpit
      - EMAIL_SMTP_PORT=1025
      - EMAIL_USERNAME=${EMAIL_USERNAME:-test@example.com}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD:-}
      - EMAIL_FROM=${EMAIL_FROM:-test@example.com}
      - EMAIL_USE_TLS=false
      - EMAIL_USE_SSL=false
      # App settings
      - SECRET_KEY=${SECRET_KEY:-staging-secret-key-change-in-production}
      - DEBUG=false
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      minio:
        condition: service_healthy
      mailpit:
        condition: service_healthy
    networks:
      - ocr_network_staging
    profiles:
      - staging

volumes:
  postgres_data_staging:
    driver: local
  redis_data_staging:
    driver: local
  minio_data_staging:
    driver: local

networks:
  ocr_network_staging:
    driver: bridge 