version: '3.8'

services:
  # Production-specific overrides
  app:
    build:
      target: production
    environment:
      - DEBUG=false
      - ENVIRONMENT=production
      - UVICORN_RELOAD=0
    volumes:
      - ../:/app
      - /app/.venv
    ports:
      - "8002:8000"  # Different port for production
    deploy:
      resources:
        limits:
          memory: 4G
          cpus: '4.0'
        reservations:
          memory: 2G
          cpus: '1.0'
    restart: always

  celery_worker_ocr:
    build:
      target: production
    environment:
      - DEBUG=false
      - ENVIRONMENT=production
    volumes:
      - ../:/app
      - /app/.venv
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '2.0'
        reservations:
          memory: 1G
          cpus: '0.5'
    restart: always

  celery_worker_media:
    build:
      target: production
    environment:
      - DEBUG=false
      - ENVIRONMENT=production
    volumes:
      - ../:/app
      - /app/.venv
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '2.0'
        reservations:
          memory: 1G
          cpus: '0.5'
    restart: always

  celery_beat:
    build:
      target: production
    environment:
      - DEBUG=false
      - ENVIRONMENT=production
    volumes:
      - ../:/app
      - /app/.venv
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.1'
    restart: always

  # Production database with high resources
  postgres:
    ports:
      - "5434:5432"  # Different port for production
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 1G
    restart: always

  redis:
    ports:
      - "6381:6379"  # Different port for production
    command: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD:-} --maxmemory 512mb --maxmemory-policy allkeys-lru
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 256M
    restart: always

  minio:
    ports:
      - "9004:9000"  # Different API port for production
      - "9005:9001"  # Different console port for production
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 256M
    restart: always

  # Remove mailpit from production
  mailpit:
    profiles:
      - disabled 