version: '3.8'

services:
  # Development-specific overrides
  app:
    build:
      target: development
    environment:
      - DEBUG=true
      - ENVIRONMENT=development
      - UVICORN_RELOAD=1
      - PYTHONUNBUFFERED=1
    volumes:
      - ../:/app
      - /app/.venv
    ports:
      - "8000:8000"
      - "5678:5678"  # Debug port
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '1.0'
        reservations:
          memory: 512M
          cpus: '0.25'

  celery_worker_ocr:
    build:
      target: development
    environment:
      - DEBUG=true
      - ENVIRONMENT=development
    volumes:
      - ../:/app
      - /app/.venv
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.1'

  celery_worker_media:
    build:
      target: development
    environment:
      - DEBUG=true
      - ENVIRONMENT=development
    volumes:
      - ../:/app
      - /app/.venv
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.1'

  celery_beat:
    build:
      target: development
    environment:
      - DEBUG=true
      - ENVIRONMENT=development
    volumes:
      - ../:/app
      - /app/.venv
    deploy:
      resources:
        limits:
          memory: 128M
          cpus: '0.25'
        reservations:
          memory: 64M
          cpus: '0.05'

  # Development database with reduced resources
  postgres:
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

  redis:
    command: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD:-} --maxmemory 128mb --maxmemory-policy allkeys-lru
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 64M

  minio:
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 64M

  mailpit:
    deploy:
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 32M 